# 网络配置
network:
  tle_file: "configs/Iridium_TLEs.txt"
  max_distance: 4000.0  # km

# 能源配置
energy:
  config_file: "configs/energy_config.yaml"
  
# 联邦学习配置
fl:
  num_satellites: 66  # 总卫星数量
  satellites_per_orbit: 11  # 每轨道卫星数
  num_orbits: 6  # 轨道数量
  num_rounds: 20
  round_interval: 300  # 每轮训练间隔(秒)
  
# 数据配置
data:
  feature_dim: 10
  num_classes: 2
  total_samples: 66000  # 增加总样本数以适应更多卫星
  test_samples: 1000
  dirichlet_alpha: 0.5
  mean_samples_per_satellite: 1000  # 每个卫星的平均样本数
  
# 模型配置
model:
  hidden_dim: 20
  
# 客户端配置
client:
  batch_size: 32
  local_epochs: 5
  learning_rate: 0.01
  momentum: 0.9
  compute_capacity: 1.0
  storage_capacity: 1000.0
  
# 聚合配置
aggregation:
  min_updates: 2
  max_staleness: 300.0
  timeout: 600.0
  weighted_average: true

# 地面站配置
ground_station:
  bandwidth_limit: 1000.0  # Mbps
  storage_limit: 10000.0   # MB
  priority_levels: 3
  batch_size: 10
  aggregation_interval: 60.0