default:
  battery_capacity: 1000.0    # 电池容量(Wh)
  solar_panel_area: 2.5       # 太阳能板面积(m²)
  solar_efficiency: 0.3       # 太阳能转换效率
  cpu_power: 15.0            # CPU功耗(W)
  radio_power_idle: 2.0      # 通信模块空闲功耗(W)
  radio_power_tx: 20.0       # 通信模块发送功耗(W)
  radio_power_rx: 10.0       # 通信模块接收功耗(W)