# 网络配置
network:
  tle_file: "configs/Iridium_TLEs.txt"
  max_distance: 4000.0  # km

# 能源配置
energy:
  config_file: "configs/energy_config.yaml"
  
# 联邦学习配置
fl:
  num_satellites: 66  # 总卫星数量
  satellites_per_orbit: 11  # 每轨道卫星数
  num_orbits: 6  # 轨道数量
  num_rounds: 20
  round_interval: 300  # 每轮训练间隔(秒)
  
# FedAvg特定配置
fedavg:
  participation_rate: 0.3  # 每轮参与比例
  
# # 数据配置
# data:
#   dataset: "network_traffic"  # 使用与主实验相同的数据集
#   dirichlet_alpha: 0.5
#   mean_samples_per_satellite: 1000
#   test_samples: 10000
#   total_samples: 66000
#   malicious_ratio: 0.3
#   orbit_similarity: 0.7
#   position_similarity: 0.8

# 数据配置
data:
  dataset: "mnist"  # 新增数据集类型标识
  dirichlet_alpha: 0.5
  mean_samples_per_satellite: 1000
  test_samples: 10000
  total_samples: 66000

# # 模型配置
# model:
#   type: "traffic_classifier"
#   hidden_dim: 20
#   batch_size: 64
#   learning_rate: 0.01
#   momentum: 0.5

# 模型配置
model:
  type: "cnn"
  batch_size: 64
  learning_rate: 0.01
  momentum: 0.5
  
# 客户端配置
client:
  batch_size: 32
  local_epochs: 5
  learning_rate: 0.01
  momentum: 0.9
  compute_capacity: 1.0
  storage_capacity: 1000.0

# 聚合配置
aggregation:
  min_updates: 2
  max_staleness: 300.0
  timeout: 600.0
  weighted_average: true
