# configs/propagation_fedprox_config.yaml
fl:
  num_rounds: 20
  round_interval: 3600  # 1小时
  num_satellites: 66
  num_orbits: 6
  satellites_per_orbit: 11

data:
  dataset: "real_traffic"  # 使用真实网络流量数据
  csv_path: "/Users/yuboli/Downloads/merged_traffic_data_20250305_111338.csv"
  total_samples: 100000
  test_samples: 10000
  iid: false
  alpha: 1.0
  dirichlet_alpha: 0.5
  mean_samples_per_satellite: 1000
  region_similarity: true
  overlap_ratio: 0.5

client:
  local_epochs: 3
  batch_size: 32
  learning_rate: 0.01
  momentum: 0.9
  shuffle: true
  optimizer: sgd
  weight_decay: 0.0001

aggregation:
  min_updates: 2
  max_staleness: 2
  timeout: 600.0
  weighted_average: true

model:
  hidden_dim: 64

network:
  tle_file: "configs/Iridium_TLEs.txt"
  max_distance: 4000.0  # km

energy:
   config_file: "configs/energy_config.yaml"


# FedProx特有参数
fedprox:
  mu: 0.1  # 接近性项系数

# 传播相关参数
propagation:
  hops: 2  # 传播跳数
  max_satellites: 24  # 设置为与您的方法相近的卫星数
  intra_orbit_links: true  # 启用轨道内链接
  inter_orbit_links: true  # 启用轨道间链接
  link_reliability: 0.95  # 链接可靠性
  energy_per_hop: 0.05  # 每跳能耗